// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApp.Models;

#nullable disable

namespace WeatherApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505111946_SeedCities")]
    partial class SeedCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WeatherApp.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 59.909999999999997,
                            Longitude = 10.75,
                            Name = "Oslo"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 59.329999999999998,
                            Longitude = 18.059999999999999,
                            Name = "Stockholm"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 55.670000000000002,
                            Longitude = 12.56,
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 52.520000000000003,
                            Longitude = 13.4,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 48.850000000000001,
                            Longitude = 2.3500000000000001,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 51.5,
                            Longitude = -0.12,
                            Name = "London"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 40.409999999999997,
                            Longitude = -3.7000000000000002,
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 41.899999999999999,
                            Longitude = 12.49,
                            Name = "Rome"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 60.170000000000002,
                            Longitude = 24.940000000000001,
                            Name = "Helsinki"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 52.369999999999997,
                            Longitude = 4.9000000000000004,
                            Name = "Amsterdam"
                        });
                });

            modelBuilder.Entity("WeatherApp.Models.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Weathers");
                });

            modelBuilder.Entity("WeatherApp.Models.Weather", b =>
                {
                    b.HasOne("WeatherApp.Models.City", "City")
                        .WithMany("Weathers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WeatherApp.Models.City", b =>
                {
                    b.Navigation("Weathers");
                });
#pragma warning restore 612, 618
        }
    }
}
